#define GPIO_MODE_CONF							((uint32_t)0xF)

#define GPIO_MODE_INPUT							((uint32_t)0x0)
#define GPIO_MODE_OUTPUT_10MHz			((uint32_t)0x1)
#define GPIO_MODE_OUTPUT_02MHz			((uint32_t)0x2)
#define GPIO_MODE_OUTPUT_50MHz			((uint32_t)0x3)

#define GPIO_CONF_INPUT_ANALOG			((uint32_t)0x0)
#define GPIO_CONF_INPUT_FLOATING		((uint32_t)0x4)
#define GPIO_CONF_INPUT_PULL				((uint32_t)0x8)
#define GPIO_CONF_OUTPUTG_PUSHPULL	((uint32_t)0x0)
#define GPIO_CONF_OUTPUTG_OPENDRAIN	((uint32_t)0x4)
#define GPIO_CONF_OUTPUTA_PUSHPULL	((uint32_t)0x8)
#define GPIO_CONF_OUTPUTA_OPENDRAIN	((uint32_t)0xC)

#define GPIO_PORT										(0x4)
#define GPIO_PORT_0									(0*GPIO_PORT)
#define GPIO_PORT_1									(1*GPIO_PORT)
#define GPIO_PORT_2									(2*GPIO_PORT)
#define GPIO_PORT_3									(3*GPIO_PORT)
#define GPIO_PORT_4									(4*GPIO_PORT)
#define GPIO_PORT_5									(5*GPIO_PORT)
#define GPIO_PORT_6									(6*GPIO_PORT)
#define GPIO_PORT_7									(7*GPIO_PORT)
